name: habit_hero
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  camera: ^0.11.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

flutter_native_splash:
  color: "#e1f5fe"
  image: lib/assets/icons/splash.png
  color_dark: "#121212"
  image_dark: lib/assets/icons/splash.png
  ios: false
  web: false
