name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [reopened, ready_for_review, synchronize, opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: 18

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
